spring:
  application:
    name: parrains
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parrains?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Ajout du dialecte
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: "classpath*:data.sql"
      mode: always
  security:
    jwt:
      secret: "@LAFIN2LAFOIREONCOMPTELESBOUSES"
      expiration: 604800000  # 1 semaine en millisecondes

server:
  servlet:
    context-path: /api  # Définit le préfixe /api pour toutes les routes

springdoc:
  api-docs:
    path: /public/documentation
  swagger-ui:
    path: /public/documentation
