spring:
  application:
    name: parrains
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parrains?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: "classpath*:data.sql"
      mode: always
  security:
    jwt:
      secret: "ALAFINDELAFOIREONCOMPTELESBOUSES"
      expiration: 604800000  # 1 semaine en millisecondes
