spring:
  application:
    name: parrains
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parrains?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: "classpath*:data.sql"
      mode: always
server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: /public/documentation
  swagger-ui:
    path: /public/documentation
application:
  security:
    jwt:
      secret: a656f4f87edae419df63fc317ed353be1f17f43efd6ab60b9d10110fa25ab746
      expiration: 604800000  # 1 semaine en millisecondes

